name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'Dockerfile', '.dockerignore','pom.xml', 'src/**', '.github/workflows/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'Dockerfile', '.dockerignore', 'pom.xml', 'src/**', '.github/workflows/**' ]

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  build-test: 
    name: Build and test
    strategy:   
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
        exclude:
          - os: windows-latest
            java: 21
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Test
        run: mvn -B -DskipTests=false test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-${{ matrix.os }}-java${{ matrix.java }}
          path: target/surefire-reports

      - name: Upload compiled classes
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest' && matrix.java == 21
        with:
          name: compiled-classes
          path: target/classes


      - name: Upload JaCoCo HTML (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-site-${{ matrix.os }}-java${{ matrix.java }}
          path: target/site/jacoco

    
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: target/classes

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.CICD_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=traunmus_ci-cd-uebung-traunmueller
            -Dsonar.organization=traunmus
            -Dsonar.branch.name=main
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  docker: 
    name: Docker build
    needs: sonar
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps: 
      - uses: actions/checkout@v4

      - name: Set up JDK (warm up Maven cache for build stage)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Set up DockerBuildx
        uses: docker/setup-buildx-action@v3

      - name: Compute SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build 
        uses: docker/build-push-action@v6
        with: 
          context: .
          platforms: linux/amd64
          load: true
          tags: local/app:${{ steps.vars.outputs.short_sha }}
      
      - name: Save image
        run: docker save -o image-${{ steps.vars.outputs.short_sha }}.tar local/app:${{ steps.vars.outputs.short_sha }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: docker-image-${{ steps.vars.outputs.short_sha }}
          path: image-${{ steps.vars.outputs.short_sha }}.tar
          retention-days: 7

  vulnerability_Scan_trivy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Download image artifactg
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ needs.docker.outputs.short_sha }}

      - name: Load docker image from artifact
        run: docker load -i image-${{ needs.docker.outputs.short_sha }}.tar

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.33.1
        continue-on-error: true
        with:
          image-ref: local/app:${{ needs.docker.outputs.short_sha }}
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
                          


      - name: Trivy Image Scan (JSON Report)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: local/app:${{ needs.docker.outputs.short_sha }}
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          format: 'json'                    # <-- wichtig
          output: 'trivy-image-report.json' # <-- wird im Workspace erzeugt
                       

      - name: Upload Trivy JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.json
          retention-days: 7

      - name: Scan IaC
        uses: aquasecurity/trivy-action@0.33.1
        continue-on-error: true
        with:
          scan-type: 'config'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      

  vulnerability_Scan_Grype:
    runs-on: ubuntu-latest
    name: Vulnerability Scan with Grype
    needs: docker
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ needs.docker.outputs.short_sha }}

      - name: Load docker image from artifact
        run: docker load -i image-${{ needs.docker.outputs.short_sha }}.tar

      - name: Scan Docker Image with Grype
        uses: anchore/scan-action@v6
        with:
          image: local/app:${{ needs.docker.outputs.short_sha }}
          fail-build: false
          output-format: json
          output-file: grype-report.json
       

      - name: Upload Grype JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: grype-image-report
          path: grype-report.json
          retention-days: 7